name: Run Tests
on: push

jobs: 
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    env: 
      COMPOSE_FILE: Dockerfile

    steps: 
    - name: Checkout code
      uses: action/checkout@v4

    - name: Build docker images
      run: docker build -t main -p $COMPOSE_FILE .

    - name: Run Tests
      run: docker run main